openapi: 3.0.1
info:
  contact: {}
  description: The responses of the open api in swagger focus on the data field rather
    than the code and the message fields
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rainbow-API
  version: "1.0"
servers:
- url: http://127.0.0.1:8080/v0
- url: https://127.0.0.1:8080/v0
paths:
  /orders/summary/{trade_no}:
    get:
      description: query order summary by trade no
      operationId: QueryOrderSummary
      parameters:
      - description: trade no
        in: path
        name: trade_no
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.Order'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Internal Server error
      summary: query order summary by trade no
      tags:
      - Orders
  /orders/wechat:
    post:
      description: make order
      operationId: MakeOrder
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/services.MakeWechatOrderReq'
        description: make_wechat_order_req
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.Order'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Internal Server error
      summary: Make Order
      tags:
      - Orders
      x-codegen-request-body-name: wecaht_ord_req
  /orders/wechat/refresh-url/{trade_no}:
    post:
      description: refresh pay url
      operationId: RefreshPayUrl
      parameters:
      - description: trade no
        in: path
        name: trade_no
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/services.MakeOrderResp'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Internal Server error
      summary: refresh pay url
      tags:
      - Orders
  /orders/wechat/{trade_no}:
    get:
      description: query order by trade no
      operationId: QueryWechatOrderDetail
      parameters:
      - description: trade no
        in: path
        name: trade_no
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.WechatOrderDetail'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cns_errors.RainbowErrorDetailInfo'
          description: Internal Server error
      summary: query order by trade no
      tags:
      - Orders
components:
  schemas:
    cns_errors.RainbowErrorDetailInfo:
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    gorm.DeletedAt:
      example:
        valid: true
        time: time
      properties:
        time:
          type: string
        valid:
          description: Valid is true if Time is not NULL
          type: boolean
      type: object
    models.Order:
      example:
        amount: 0
        time_expire: time_expire
        trade_state: 5
        appName: appName
        created_at: created_at
        description: description
        trade_provider: 1
        deleted_at:
          valid: true
          time: time
        h5_url: h5_url
        updated_at: updated_at
        code_url: code_url
        trade_no: trade_no
        trade_type: 5
        id: 6
      properties:
        amount:
          description: 单位为分
          type: integer
        appName:
          type: string
        code_url:
          type: string
        created_at:
          type: string
        deleted_at:
          $ref: '#/components/schemas/gorm.DeletedAt'
        description:
          type: string
        h5_url:
          type: string
        id:
          type: integer
        time_expire:
          type: string
        trade_no:
          type: string
        trade_provider:
          type: integer
        trade_state:
          type: integer
        trade_type:
          type: integer
        updated_at:
          type: string
      type: object
    models.WechatOrderDetail:
      example:
        transaction_id: transaction_id
        amount: 0
        mchid: mchid
        trade_state: trade_state
        bank_type: bank_type
        created_at: created_at
        success_time: success_time
        deleted_at:
          valid: true
          time: time
        payer: payer
        updated_at: updated_at
        appid: appid
        trade_state_desc: trade_state_desc
        trade_no: trade_no
        trade_type: trade_type
        attach: attach
        id: 6
      properties:
        amount:
          type: integer
        appid:
          type: string
        attach:
          type: string
        bank_type:
          type: string
        created_at:
          type: string
        deleted_at:
          $ref: '#/components/schemas/gorm.DeletedAt'
        id:
          type: integer
        mchid:
          type: string
        payer:
          type: string
        success_time:
          type: string
        trade_no:
          type: string
        trade_state:
          type: string
        trade_state_desc:
          type: string
        trade_type:
          type: string
        transaction_id:
          type: string
        updated_at:
          type: string
      type: object
    services.MakeOrderResp:
      example:
        h5_url: h5_url
        code_url: code_url
        trade_no: trade_no
        trade_type: 6
        trade_provider: 0
      properties:
        code_url:
          type: string
        h5_url:
          type: string
        trade_no:
          type: string
        trade_provider:
          type: integer
        trade_type:
          type: integer
      type: object
    services.MakeWechatOrderReq:
      properties:
        amount:
          type: integer
        description:
          type: string
        time_expire:
          type: integer
        trade_type:
          type: integer
      required:
      - amount
      - description
      - time_expire
      - trade_type
      type: object
x-original-swagger-version: "2.0"
